---
title: jimdab.com
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: jimdab@jimdab.com
description: "Welcome to my own little corner of the web where I will continue to
  try to practice my writing by sharing my thoughts. \n"
baseurl: ''
url: http://jimdab.com
markdown: kramdown
# Build settings
theme: minima
plugins:
  - jekyll-feed
