# Site settings
title: jimdab.com
email: jimdab@jimdab.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my own little corner of the web where I will continue to try to practice my writing by sharing my thoughts. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jimdab.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman